### PR TITLE
Use pthread instead of mostly unsupported C11 threads

### PR DESCRIPTION
**Pull request by saraedum**

### CODE REVIEW

**Comment by krytarowski** [comment]
Why unsupported? NetBSD, Linux, FreeBSD, Illumos support them. For proprietary OSs there are thin shims.

**Comment by videlec** [comment]
Let say "less supported". We are not using anything fancy about threads and we don't want any user to go through any extra complication.

**Comment by krytarowski** [comment]
POSIX can become threads are less portable than C11 threads... also POSIX can mandate C11 threads in not so long term, they are already discussing how to standardize it.

**Comment by saraedum** [comment]
@krytarowski I think mostly unsupported still fits unless I totally misunderstand. Unless we want to use some shim, glibc only shipped C11 thread support in 2.28 which was released in August 2018 which is e.g. only in Debian buster.

**Comment by krytarowski** [comment]
It will certainly take some years until it will be ubiquitous, but I wouldn't call it 'mostly unsupported' as of today. NetBSD will support it since 9.0.

**Pull request merged**
