### PR TITLE
Make pthread optional

### LINKED ISSUE #41: make pthread support optional

### PR DESCRIPTION
**Pull request by saraedum**
fixes #41

### CODE REVIEW

**Comment by videlec** [comment]
Should we run both versions with and without pthreads in CI?

**Comment by videlec** [comment]
And I noticed that renf/test/t-thread.c:23-26
```
typedef struct {
    renf_ptr nf;
    int err;
} thread_data;
```
is actually not used anywhere in the test.

**Comment by saraedum** [comment]
Yes, and I removed that part of the code.

**Comment by saraedum** [comment]
I don't think we have to test both compilers with & without pthread so I just made the switch for gcc.

**Comment by videlec** [comment]
thank you

**Pull request merged**
