### PR TITLE
Remove fmpq_t from renf_elem_class

### LINKED ISSUE #28: remove support for rationals in renf_elem_class
The `renf_elem_class` is a fake union type of `renf_elem_class` and `fmpq_t`. Because of this, a lot of code in the C++ interface is just dedicated to the proper dispatch. Since the GMP C++ classes `mpz_class` and `mpq_class` are fully compatible with `renf_elem_class` we should just get rid of this fake union type and have `renf_elem_class` to carry only the two attributes
```
renf * nf; // parent number field
renf_elem_t a; // the actual element
```

### PR DESCRIPTION
**Pull request by saraedum**
fixes #28.

### CODE REVIEW

**Comment by saraedum** [comment]
@videlec any idea what needs to happen to make Travis CI run?

**Comment by videlec** [comment]
weird...

**Comment by saraedum** [comment]
Whatever you did, that brought things back to live :)

**Comment by saraedum** [comment]
@videlec tests pass now. I think this is ready for inclusion.

**Pull request merged**
