### PR TITLE
Autoconfiscation

### PR DESCRIPTION
**Pull request by mkoeppe**

### CODE REVIEW

**Comment by videlec** [comment]
Fantastic! Using your branch, I first realized that ./configure works even without m4 installed. I just got a warning about that

    aclocal: warning: couldn't open directory 'm4': No such file or directory

Would it be possible to raise an error if some program is not present?

On the other hand (after installing m4), the linker produces a warning (some of it in french)

    copying selected object files to avoid basename conflicts...
    ar: `u' modifier ignored since `D' is the default (see `U')

Is that expected?

**Comment by mkoeppe** [comment]
It's not really complaining about m4, rather about the m4/ subdirectory. Added it to git.

**Comment by videlec** [comment]
I see. Thanks.

**Comment by mkoeppe** [comment]
I think it is safe to ignore ar's warning.

**Comment by videlec** [comment]
Looks good. I was able to compile normaliz as well! Thanks!

**Comment by videlec** [comment]
About the ar issue, it seems to be a bug https://bugzilla.redhat.com/show_bug.cgi?id=1155273

**Comment by mkoeppe** [comment]
Thanks for the pointer. Fortunately, not our problem.

**Pull request merged**
